import { alpha, type Components, type Theme } from '@mui/material/styles';
import { designTokens } from '../../foundations/tokens';
import type { OverrideContext } from './types';

export const buttonOverrides = ({ mode, tokens: t }: OverrideContext): Components<Theme> => ({
  MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: {
    root: { minHeight: 48, fontWeight: 500, boxShadow: 'none', transition: 'transform .2s ease, background-color .2s ease', '&:active': { transform: 'scale(.98)' } },
    containedPrimary: { background: designTokens.color.primaryContainer, color: designTokens.color.onPrimary, borderRadius: 48, padding: '12px 24px', '&:hover': { background: designTokens.color.primary }, '&:active': { background: designTokens.color.primary } },
    outlined: { borderColor: t.borderGray, color: t.textPrimary, borderRadius: 8, backgroundColor: alpha(t.textPrimary, mode === 'dark' ? .04 : .03), padding: '12px 16px', '&:hover': { backgroundColor: t.surfaceOffWhite, borderColor: t.outline } },
  }, variants: [
    { props: { variant: 'segmented' }, style: { minHeight: 40, height: 40, borderRadius: 16, padding: '0 8px', border: `1px solid ${t.borderGray}`, backgroundColor: t.surfacePure, color: t.textPrimary, fontSize: 11, fontWeight: 600, '&:hover': { backgroundColor: t.surfaceOffWhite, borderColor: t.borderGray } } },
    { props: { variant: 'segmentedSelected' }, style: { minHeight: 40, height: 40, borderRadius: 16, padding: '0 8px', border: '1px solid transparent', backgroundColor: designTokens.color.secondary, color: designTokens.color.onSecondary, fontSize: 11, fontWeight: 700, '&:hover': { backgroundColor: designTokens.color.secondary } } },
    { props: { variant: 'keypad' }, style: { minHeight: 60, height: 60, borderRadius: 16, border: `1px solid ${t.borderGray}`, backgroundColor: t.surfacePure, color: t.textPrimary, fontSize: 20, fontWeight: 700, boxShadow: 'none', touchAction: 'manipulation', userSelect: 'none', WebkitTapHighlightColor: 'transparent', '&:hover': { backgroundColor: t.surfaceOffWhite }, '&:active': { backgroundColor: alpha(designTokens.color.primaryContainer, .12), transform: 'scale(.95)' } } },
    { props: { variant: 'keypadBack' }, style: { minHeight: 60, height: 60, borderRadius: 16, border: `1px solid ${t.borderGray}`, backgroundColor: t.surfaceOffWhite, color: t.textPrimary, fontSize: 20, fontWeight: 700, boxShadow: 'none', touchAction: 'manipulation', userSelect: 'none', WebkitTapHighlightColor: 'transparent', '&:hover': { backgroundColor: t.surfaceContainerHigh }, '&:active': { transform: 'scale(.95)' } } },
    { props: { variant: 'compactField' }, style: { minHeight: 56, height: 56, borderRadius: 16, border: `1px solid ${t.borderGray}`, backgroundColor: t.surfaceOffWhite, color: t.textSecondary, fontSize: 13.5, fontWeight: 500, padding: '0 16px', '&:hover': { backgroundColor: t.surfaceContainerHigh, borderColor: t.borderGray } } },
    { props: { variant: 'primaryAction' }, style: { minHeight: 56, height: 56, borderRadius: 16, backgroundColor: designTokens.color.primary, color: designTokens.color.onPrimary, fontSize: 16, fontWeight: 700, '&:hover': { backgroundColor: designTokens.color.primaryContainer } } },
    { props: { variant: 'assistantPrompt' }, style: { minHeight: 112, height: 112, borderRadius: 20, padding: 16, justifyContent: 'flex-start', alignItems: 'stretch', textAlign: 'left', border: `1px solid ${t.borderGray}`, backgroundColor: t.surfaceOffWhite, color: t.textPrimary, boxShadow: 'none', '&:hover': { backgroundColor: t.surfaceContainerHigh, borderColor: t.borderGray } } },
    { props: { variant: 'assistantPromptFeatured' }, style: { minHeight: 112, height: 112, borderRadius: 20, padding: 16, justifyContent: 'flex-start', alignItems: 'stretch', textAlign: 'left', border: `1px solid ${designTokens.color.secondary}`, backgroundColor: designTokens.color.secondary, color: designTokens.color.onSecondary, boxShadow: 'none', '&:hover': { backgroundColor: designTokens.color.secondary, borderColor: designTokens.color.secondary } } },
    { props: { variant: 'assistantSend' }, style: { width: 40, minWidth: 40, height: 40, minHeight: 40, padding: 0, borderRadius: 48, backgroundColor: designTokens.color.primary, color: designTokens.color.onPrimary, '&:hover': { backgroundColor: designTokens.color.primaryContainer }, '&.Mui-disabled': { backgroundColor: t.surfaceOffWhite, color: t.disabled } } },
  ] },
  MuiIconButton: { styleOverrides: { root: { color: t.outline, borderRadius: 48, height: 48, width: 48, transition: 'background-color .2s ease, color .2s ease', '&:hover': { backgroundColor: t.surfaceOffWhite, color: t.textPrimary } } } },
});
